enum ActionTypesEnum {
  CHANGE_VISUALIZED_TIME_MODE = "CHANGE_VISUALIZED_TIME_MODE",
  ADD_TIMELINE = "ADD_TIMELINE",
  UPDATE_FORM_ITEMS_VALUE = "UPDATE_FORM_ITEMS_VALUE",
  COVER_FORM_ITEMS = "COVER_FORM_ITEMS",
}

export default ActionTypesEnum;
